#!/usr/bin/php
<?php

require_once 'init.php';

$conf = array(
	'models_path' => dirname( __FILE__ ),
	'yaml_schema_path' => dirname( __FILE__ ) . '/db/schema',
	'data_fixtures_path' => dirname( __FILE__ ) . '/db/fixtures',
	'generate_models_options' => array(
		'pearStyle' => true,
		'classPrefix' => 'Model_Dao_',
		'baseClassPrefix' => 'Base_',
		'baseClassesDirectory' => '',
		'generateTableClasses' => true
	),
);

$cli = new Doctrine_Cli( $conf );
$cli->run( $_SERVER['argv'] );