<?php

/**
 * Model_Dao_Base_ProductL10n
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property string $cldr
 * @property string $title
 * @property string $summary
 * @property Model_Dao_Product $Product
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Dao_Base_ProductL10n extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_l10n');
        $this->hasColumn('product_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('cldr', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('summary', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Dao_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}