<?php

/**
 * Model_Dao_ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_Dao_ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_Dao_ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Dao_Product');
    }
}