<?php

/**
 * Model_Dao_ProductL10nTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_Dao_ProductL10nTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_Dao_ProductL10nTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Dao_ProductL10n');
    }
}